### ISSUE TITLE
blockchain: implement blockchain spec

### ISSUE THREAD

**Issue by vickiniu** [stellar/slingshot#277]
Tracking issue for tasks in the blockchain spec

Data types
- [x] [blockchain state](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#blockchain-state), done in #264 
- [x] [block](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#block), done in #264
- [x] [block header](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#block-header), done in #264
- [x] [block id](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#block-id), done in #264

Procedures
- [x] [start new network](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#start-new-network)
- [x] [make initial block header](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#make-initial-block-header), done in #264
- [x] [join existing network](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#join-existing-network)
- [x] [validate block](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#validate-block), done in #264 
- [x] [make block](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#make-block)
- [x] [execute tx list](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#execute-transaction-list), wip in #276 
- [x] [apply block](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#apply-block), done in #264 
- [x] [apply tx list](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#apply-transaction-list), closed (can build iterator of apply tx log)
- [x] [apply tx log](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#apply-transaction-log), done in #275 
- [x] [compute txroot](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#compute-txroot), done in #280 
- [x] [compute utxoroot](https://github.com/interstellar/slingshot/blob/main/zkvm/docs/zkvm-blockchain.md#compute-utxoroot), done in #280

**Comment by oleganza** [comment]
Last update: #308
