### ISSUE TITLE
zkvm: rename Data type into String type

### ISSUE THREAD

**Issue by oleganza** [stellar/slingshot#309]
- [x] rename `Data` into `String` #329
- [x] change wording in the spec from `a data type` to `a string` https://github.com/stellar/slingshot/pull/324
- [x] change wording in the spec from `a program type` to `a program` #329
- [x] change wording in the spec from `a contract type` to `a contract` #329

**Comment by oleganza** [comment]
Rationale: 

* https://github.com/stellar/slingshot/pull/304#discussion_r285241119
* https://github.com/stellar/slingshot/pull/304#discussion_r285244693
