### ISSUE TITLE
Demo checklist

### ISSUE THREAD

**Issue by oleganza** [stellar/slingshot#355]
- [x] Each account runs a separate node. #354
- [x] Sqlite backend. #354
- [x] Send and receive money. #354
- [ ] Mempool to manually create multi-tx blocks.
- [ ] Add new users.
- [ ] Issue new assets.
- [ ] Show human-readable program.
- [ ] Show structure of inputs/outputs.
- [ ] Show annotated txs for accounts.
- [ ] Postgres support.
